-- ==========================================
-- Oracle Database 21c XE Deployment DDL Script
-- Project: FraudGuard AI
-- ==========================================

-- Drop existing structures if they exist
-- DROP PROCEDURE SP_GET_FRAUD_SUMMARY;
-- DROP VIEW V_FRAUD_DETAILS;
-- DROP TABLE EMAIL_VERIFICATION_TOKENS;
-- DROP TABLE PASSWORD_RESET_TOKENS;
-- DROP TABLE NOTIFICATIONS;
-- DROP TABLE LOGIN_SESSIONS;
-- DROP TABLE AUDIT_LOGS;
-- DROP TABLE FRAUD_RESULTS;
-- DROP TABLE TRANSACTIONS;
-- DROP TABLE USER_ROLES;
-- DROP TABLE USERS;
-- DROP TABLE ROLES;
-- DROP SEQUENCE SEQ_ROLES;
-- DROP SEQUENCE SEQ_USERS;
-- DROP SEQUENCE SEQ_TRANSACTIONS;
-- DROP SEQUENCE SEQ_FRAUD_RESULTS;
-- DROP SEQUENCE SEQ_AUDIT_LOGS;
-- DROP SEQUENCE SEQ_LOGIN_SESSIONS;
-- DROP SEQUENCE SEQ_NOTIFICATIONS;
-- DROP SEQUENCE SEQ_PASSWORD_RESET_TOKENS;
-- DROP SEQUENCE SEQ_EMAIL_VERIFICATION_TOKENS;

-- 1. Create Sequences
CREATE SEQUENCE SEQ_ROLES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TRANSACTIONS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FRAUD_RESULTS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AUDIT_LOGS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_LOGIN_SESSIONS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_NOTIFICATIONS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PASSWORD_RESET_TOKENS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EMAIL_VERIFICATION_TOKENS START WITH 1 INCREMENT BY 1 NOCACHE;

-- 2. Create Tables
CREATE TABLE ROLES (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE USERS (
    id NUMBER PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    full_name VARCHAR2(150) NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    locked NUMBER(1) DEFAULT 0 NOT NULL,
    failed_login_attempts NUMBER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE USER_ROLES (
    user_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_oracle_ur_user FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
    CONSTRAINT fk_oracle_ur_role FOREIGN KEY (role_id) REFERENCES ROLES(id) ON DELETE CASCADE
);

CREATE TABLE TRANSACTIONS (
    id NUMBER PRIMARY KEY,
    account_number VARCHAR2(50) NOT NULL,
    amount NUMBER(15,2) NOT NULL,
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    location VARCHAR2(150) NOT NULL,
    device VARCHAR2(150) NOT NULL,
    status VARCHAR2(50) NOT NULL
);

CREATE TABLE FRAUD_RESULTS (
    id NUMBER PRIMARY KEY,
    transaction_id NUMBER NOT NULL UNIQUE,
    fraud_score NUMBER(5,2) NOT NULL,
    risk_level VARCHAR2(50) NOT NULL,
    fraud_reason VARCHAR2(1000) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_oracle_fr_tx FOREIGN KEY (transaction_id) REFERENCES TRANSACTIONS(id) ON DELETE CASCADE
);

CREATE TABLE AUDIT_LOGS (
    id NUMBER PRIMARY KEY,
    username VARCHAR2(100) NOT NULL,
    action VARCHAR2(255) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ip_address VARCHAR2(50) NOT NULL,
    browser VARCHAR2(150) NOT NULL,
    module VARCHAR2(100) NOT NULL
);

CREATE TABLE LOGIN_SESSIONS (
    id NUMBER PRIMARY KEY,
    username VARCHAR2(100) NOT NULL,
    login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    logout_time TIMESTAMP NULL,
    ip_address VARCHAR2(50) NOT NULL,
    browser VARCHAR2(150) NOT NULL,
    token VARCHAR2(1000) NOT NULL
);

CREATE TABLE NOTIFICATIONS (
    id NUMBER PRIMARY KEY,
    message VARCHAR2(1000) NOT NULL,
    read_status NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    target_role VARCHAR2(50) NOT NULL
);

CREATE TABLE PASSWORD_RESET_TOKENS (
    id NUMBER PRIMARY KEY,
    token VARCHAR2(255) NOT NULL UNIQUE,
    user_id NUMBER NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    CONSTRAINT fk_oracle_prt_user FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);

CREATE TABLE EMAIL_VERIFICATION_TOKENS (
    id NUMBER PRIMARY KEY,
    token VARCHAR2(255) NOT NULL UNIQUE,
    user_id NUMBER NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    CONSTRAINT fk_oracle_evt_user FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);

-- 3. Create Triggers for Auto-Increment Primary Keys
CREATE OR REPLACE TRIGGER TRG_BI_ROLES
BEFORE INSERT ON ROLES FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT SEQ_ROLES.NEXTVAL INTO :NEW.id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_USERS
BEFORE INSERT ON USERS FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT SEQ_USERS.NEXTVAL INTO :NEW.id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_TRANSACTIONS
BEFORE INSERT ON TRANSACTIONS FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT SEQ_TRANSACTIONS.NEXTVAL INTO :NEW.id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_FRAUD_RESULTS
BEFORE INSERT ON FRAUD_RESULTS FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT SEQ_FRAUD_RESULTS.NEXTVAL INTO :NEW.id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_AUDIT_LOGS
BEFORE INSERT ON AUDIT_LOGS FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT SEQ_AUDIT_LOGS.NEXTVAL INTO :NEW.id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_LOGIN_SESSIONS
BEFORE INSERT ON LOGIN_SESSIONS FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT SEQ_LOGIN_SESSIONS.NEXTVAL INTO :NEW.id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_NOTIFICATIONS
BEFORE INSERT ON NOTIFICATIONS FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT SEQ_NOTIFICATIONS.NEXTVAL INTO :NEW.id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_PASSWORD_RESET_TOKENS
BEFORE INSERT ON PASSWORD_RESET_TOKENS FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT SEQ_PASSWORD_RESET_TOKENS.NEXTVAL INTO :NEW.id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_EMAIL_VERIFICATION_TOKENS
BEFORE INSERT ON EMAIL_VERIFICATION_TOKENS FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT SEQ_EMAIL_VERIFICATION_TOKENS.NEXTVAL INTO :NEW.id FROM DUAL;
    END IF;
END;
/

-- 4. Create Indexes
CREATE INDEX idx_oracle_users_username ON USERS(username);
CREATE INDEX idx_oracle_tx_acc ON TRANSACTIONS(account_number);
CREATE INDEX idx_oracle_tx_date ON TRANSACTIONS(transaction_date);
CREATE INDEX idx_oracle_fr_level ON FRAUD_RESULTS(risk_level);
CREATE INDEX idx_oracle_audit_user ON AUDIT_LOGS(username);
CREATE INDEX idx_oracle_session_user ON LOGIN_SESSIONS(username);

-- 5. Create Views
CREATE OR REPLACE VIEW V_FRAUD_DETAILS AS
SELECT 
    t.id AS transaction_id,
    t.account_number,
    t.amount,
    t.transaction_date,
    t.location,
    t.device,
    t.status AS tx_status,
    f.fraud_score,
    f.risk_level,
    f.fraud_reason,
    f.created_at AS analysis_date
FROM TRANSACTIONS t
LEFT JOIN FRAUD_RESULTS f ON t.id = f.transaction_id;

-- 6. Create Stored Procedure for Fraud Summaries
CREATE OR REPLACE PROCEDURE SP_GET_FRAUD_SUMMARY(
    p_total_tx OUT NUMBER,
    p_fraud_tx OUT NUMBER,
    p_safe_tx OUT NUMBER,
    p_critical_tx OUT NUMBER
) AS
BEGIN
    -- Count total transactions
    SELECT COUNT(*) INTO p_total_tx FROM TRANSACTIONS;
    
    -- Count critical/high risk cases (score >= 60)
    SELECT COUNT(*) INTO p_fraud_tx FROM FRAUD_RESULTS WHERE fraud_score >= 60;
    
    -- Count low risk cases (score < 30)
    SELECT COUNT(*) INTO p_safe_tx FROM FRAUD_RESULTS WHERE fraud_score < 30;
    
    -- Count critical risk cases (score >= 85)
    SELECT COUNT(*) INTO p_critical_tx FROM FRAUD_RESULTS WHERE fraud_score >= 85;
END;
/
